version: '3.8'

services:
  # 1. Base de datos PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER} # Tomará esto del archivo .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432' # Puerto Host : Puerto Contenedor
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis (Para caché y colas futuras)
  redis:
    image: redis:alpine
    container_name: auth_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
